language: go
go:
- 1.3.3
before_install:
- go get github.com/tools/godep
- export PATH=$HOME/gopath/bin:$PATH
install: godep go version
script:
- godep go test -v ./...
notifications:
  email: false
  hipchat:
    rooms:
      secure: ZwhFmaWdX3/D3pU30ufAWxjr5/alcaZWl9qvBc+aj/lCRyNJuhFRl2PkT+Wf6AG7G6VFnovOXwkR/04al+qrCfRziMUuDWF7aX8PM+8aoxsPv4tcdySlOpUtBTAxkuGmAf9g9FI13KuzbYaeYDHOEFC3QwZUQMLAPQxxkZtdHXY=
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
