language: go
go:
- 1.4.2
script:
- make test
before_deploy:
- make debs
- export DEB_VERSION=$(git describe --tags --always | sed s/^v//)
notifications:
  email: false
  hipchat:
    rooms:
      secure: iA9RWtRVb+JLcUIt0dZKArASnHVeWrHSSuLGqslvI9JuLigAEszO/L29CCz/njPNj/cwDY99KIKfNIWOPuwlAZgzVQnqdMo/3OFgwQY2yNPiL+KqY6oLIPo6v3gx4mcQ2LdOdZ6YT2TgboK5gLYPI+ljZXLlTBWEMheBe6U49fg=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      (<a href="%{build_url}">Details</a> | <a href="%{compare_url}">Change view</a>)'
    format: html
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cdMqjfyDdFqtEs4lJNgDjZl63OrzWQzY30xI3rKI3IBTnFKg9MMcd+6Gee8C9BXaKja43UVwdz0VWiCYD6MQbWUvM6FlF0v4FvIeVLC3KmD614VbzNa+Hc0GLBMTa6Ho3fVWjCcLrBmXqXqZPwr0GrbI6fXy/RipHmRRyaxYxCI=
  file: shh_${DEB_VERSION}_amd64.deb
  on:
    all_branches: true
    tags: true
    repo: heroku/shh
